#!/usr/bin/env python3

# Standard library imports
import json
import logging

# Internal imports
import ktp_controller.utils
from ktp_controller.settings import SETTINGS

logging.basicConfig(
    level=logging.DEBUG,
    format="%(levelname)s:%(asctime)s:%(name)s:%(funcName)s:%(lineno)d:%(message)s",
    force=True,
)


_LOGGER = logging.getLogger("examomatic-listener")


class ExamOMaticListener(ktp_controller.utils.Listener):
    def _open_websock(self):
        examomatic_password = ktp_controller.utils.readfirstline(
            SETTINGS.examomatic_password_file, encoding="ascii"
        )

        return ktp_controller.utils.open_websock(
            SETTINGS.examomatic_host,
            "/servers/ers_connection",
            params={
                "domain": SETTINGS.domain,
                "hostname": SETTINGS.hostname,
                "id": SETTINGS.id,
            },
            header={
                "Authorization": ktp_controller.utils.get_basic_auth(
                    SETTINGS.examomatic_username, examomatic_password
                )
            },
        )

    def __send_ping(self):
        self._send({"type": "ping"}, encoder=json.dumps)

    def __send_ack(self, message):
        self._send({"type": "ack", "id": message["id"]}, encoder=json.dumps)

    def _validate_message(self, message):
        try:
            message = json.loads(message)
        except Exception:
            raise ValueError("message is not JSON") from e

        if not isinstance(message, dict):
            raise ValueError("message is not a dict")

        if not "type" in message:
            raise ValueError("message does not have 'type'")

        if not isinstance(message["type"], str):
            raise ValueError("message type is not a string")

        if not "id" in message:
            raise ValueError("message does not have 'id'")

        if not isinstance(message["id"], int):
            raise ValueError("message id is not an integer")

        return message

    def _handle_validated_message(self, message):
        if message["type"] == "pong":
            return True

        self.__send_ack(message)

        if message["type"] == "change_keycode":
            _LOGGER.info("received change_keycode message from exam-o-matic")
            # self.exam_scheduler.request_keycode_change()
            return True

        if message["type"] == "refresh_exams":
            _LOGGER.info("received refresh_exams message from exam-o-matic")
            # self.exam_sync.trigger_sync_exams()
            return True

        return False

    def _on_recv_timeout(self):
        self.__send_ping()


def main():
    examomatic_listener = ExamOMaticListener()
    ktp_controller.utils.common_term_signal(examomatic_listener.quit)
    examomatic_listener.run()


if __name__ == "__main__":
    main()
