[project]
name = "ktp-controller"
version = "0.5.0rc1"
description = "ktp-controller"
authors = [{ name = "Opinsys Developers", email = "dev@opinsys.fi" }]
requires-python = ">=3.11, <3.15"
classifiers = [
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
readme = "README.md"
license = "GPL-2.0-only"
maintainers = [{ name = "Opinsys Developers", email = "dev@opinsys.fi" }]
dependencies = [
    "asyncinotify",
    "fastapi",
    "httpx",
    "uvicorn[standard]",
    "alembic",
    "psutil",
    "pydantic-settings",
    "python-multipart",
    "supervisor",
    "redis",
    "validators",
    "websockets",
]
repository = "https://github.com/puavo-org/ktp-controller"

[project.scripts]
ktp-controller-agent = "ktp_controller.agent.main:run"
ktp-controller-api = "ktp_controller.api.main:run"
ktp-controller-cli = "ktp_controller.cli.main:run"
ktp-controller-naksu2monitor = "ktp_controller.abitti2.naksu2monitor.main:run"
ktp-controller-networking = "ktp_controller.networking.main:run"
ktp-controller-supervisor-chainer = "ktp_controller.supervisor_chainer.main:run"

[dependency-groups]
dev = [
    "pytest",
    "pytest-mock",
    "httpx",
    "selenium",
    "ruff>=0.14.13",
]

[tool.uv.build-backend]
module-root = ""
module-name = "ktp_controller"

[build-system]
requires = ["uv_build>=0.9.0,<0.10.0"]
build-backend = "uv_build"
