"""Generate docs/status_report.md from the StatusReport Pydantic schema."""

import pathlib
import textwrap

from ktp_controller.examomatic.schemas import StatusReport

OUTPUT = pathlib.Path("docs/status_report.md")


def _display_name(def_key: str) -> str:
    return def_key.lstrip("_")


def _anchor(def_key: str) -> str:
    return _display_name(def_key).lower()


def _resolve_type(prop: dict, defs: dict) -> str:
    if "$ref" in prop:
        key = prop["$ref"].split("/")[-1]
        return f"[{_display_name(key)}](#{_anchor(key)})"

    if "anyOf" in prop:
        non_null = [p for p in prop["anyOf"] if p.get("type") != "null"]
        nullable = len(non_null) < len(prop["anyOf"])
        inner = _resolve_type(non_null[0], defs) if non_null else "unknown"
        return f"{inner}?" if nullable else inner

    if prop.get("type") == "array":
        item_type = _resolve_type(prop.get("items", {}), defs)
        return f"`array` of {item_type}"

    ptype = prop.get("type", "unknown")
    fmt = prop.get("format")
    if fmt == "date-time":
        return "`datetime`"
    if ptype == "string":
        return "`string`"
    if ptype == "integer":
        return "`integer`"
    if ptype == "boolean":
        return "`boolean`"
    return f"`{ptype}`"


def _notes(prop: dict) -> str:
    parts = []
    if "const" in prop:
        parts.append(f"const: `{prop['const']}`")
    if "minimum" in prop:
        parts.append(f"minimum: `{prop['minimum']}`")
    if "enum" in prop:
        values = ", ".join(f"`{v!r}`" for v in prop["enum"])
        parts.append(f"one of {values}")
    # Unwrap anyOf to check inner constraints
    if "anyOf" in prop:
        non_null = [p for p in prop["anyOf"] if p.get("type") != "null"]
        if non_null:
            inner = non_null[0]
            if "minimum" in inner:
                parts.append(f"minimum: `{inner['minimum']}`")
    return "; ".join(parts)


def _render_object(title: str, schema: dict, defs: dict, required_fields: set) -> str:
    lines = [f"## {title}\n"]

    if schema.get("enum"):
        values = ", ".join(f"`{v}`" for v in schema["enum"])
        lines.append(f"Enum — one of: {values}\n")
        return "\n".join(lines)

    props = schema.get("properties", {})
    required = set(schema.get("required", []))

    lines.append("| Field | Type | Required | Notes |")
    lines.append("|-------|------|:--------:|-------|")

    for field, prop in props.items():
        ftype = _resolve_type(prop, defs)
        req = "yes" if field in required else "no"
        note = _notes(prop)
        lines.append(f"| `{field}` | {ftype} | {req} | {note} |")

    lines.append("")
    return "\n".join(lines)


def generate() -> str:
    schema = StatusReport.model_json_schema()
    defs = schema.get("$defs", {})

    sections = []

    header = textwrap.dedent("""\
        # StatusReport

        API documentation for the `StatusReport` schema.

        Auto-generated from `ktp_controller/examomatic/schemas.py`.
        Do not edit this file manually — run `make docs` to regenerate.

    """)
    sections.append(header)

    # Root object first
    sections.append(
        _render_object("StatusReport", schema, defs, set(schema.get("required", [])))
    )

    # All referenced definitions, enums last
    objects = {k: v for k, v in defs.items() if not v.get("enum")}
    enums = {k: v for k, v in defs.items() if v.get("enum")}

    for key, defn in objects.items():
        sections.append(_render_object(_display_name(key), defn, defs, set()))

    if enums:
        sections.append("## Enumerations\n")
        for key, defn in enums.items():
            values = ", ".join(f"`{v}`" for v in defn["enum"])
            sections.append(f"### {_display_name(key)}\n\nOne of: {values}\n")

    return "\n".join(sections)


if __name__ == "__main__":
    content = generate()
    OUTPUT.write_text(content)
    print(f"Written {OUTPUT}")
