#!/bin/bash

set -euo pipefail

THIS=$(readlink -e "$0")
HERE=$(dirname "$THIS")
RUNCONF=
OS=

if [ -d /etc/puavo ]; then
    OS='Puavo OS'
fi

case "$OS" in
    '')
        echo 'Failed to detect operating system!' >&2
        exit 1
        ;;
    'Puavo OS')
        WORKDIR="$HOME/.puavo/puavo-ers/ktp-controller"
        RUNCONF='puavo_os-prod-run.conf'
        ;;
    *)
        echo "Unsupported operating system '$OS'!" >&2
        exit 1
        ;;
esac

WORKDIR=$(readlink -m "${WORKDIR}")

mkdir -p "${WORKDIR}"
mkdir -p "${WORKDIR}/logs"

cd "${WORKDIR}"

export PATH="$HERE/bin:$PATH"

if [ $# -eq 0 ]; then
    COMMAND=run
else
    COMMAND=$1
    shift
fi

case "$COMMAND" in
    bash)
        exec bash --noprofile --rcfile <(echo "PS1='KTP Controller Shell\n\u@\h $ '") -i "$@"
        ;;
    cli)
        echo "WARNING: deprecated, run instead: $0 $@" >&2
        KTP_CONTROLLER_LOGGING_LEVEL=WARNING exec ktp-controller-cli "$@"
        ;;
    shutdown)
        exec supervisorctl -c "$HERE/$RUNCONF" shutdown
        ;;
    supervisorctl)
        exec supervisorctl -c "$HERE/$RUNCONF" "$@"
        ;;
    run)
        exec supervisord -c "$HERE/$RUNCONF"
        ;;
    tui)
        exec ktp-controller-tui "$@"
        ;;
    *)
        KTP_CONTROLLER_LOGGING_LEVEL=WARNING exec ktp-controller-cli "$COMMAND" "$@"
        ;;
esac
