"""Exam info

Revision ID: 1f19e1e8fc1a
Revises: 8f68ef9389a7
Create Date: 2025-10-21 22:19:22.286664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1f19e1e8fc1a"
down_revision: Union[str, Sequence[str], None] = "8f68ef9389a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "abitti2_status_report",
        sa.Column("dbid", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("_row_created_at", sa.DateTime(), nullable=False),
        sa.Column("raw_data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("dbid"),
    )
    op.create_index(
        op.f("ix_abitti2_status_report__row_created_at"),
        "abitti2_status_report",
        ["_row_created_at"],
        unique=False,
    )
    op.create_table(
        "exam_file_info",
        sa.Column("dbid", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("_row_created_at", sa.DateTime(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("decrypt_code", sa.String(), nullable=False),
        sa.Column("modified_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("dbid"),
    )
    op.create_index(
        op.f("ix_exam_file_info_external_id"),
        "exam_file_info",
        ["external_id"],
        unique=True,
    )
    op.create_table(
        "exam_info",
        sa.Column("dbid", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("_row_created_at", sa.DateTime(), nullable=False),
        sa.Column("request_id", sa.String(), nullable=False),
        sa.Column("raw_data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("dbid"),
    )
    op.create_index(
        op.f("ix_exam_info__row_created_at"),
        "exam_info",
        ["_row_created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_exam_info_request_id"), "exam_info", ["request_id"], unique=True
    )
    op.create_table(
        "scheduled_exam_package",
        sa.Column("dbid", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("_row_created_at", sa.DateTime(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column("lock_time", sa.DateTime(), nullable=True),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("current", sa.Boolean(), nullable=True),
        sa.Column("state", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("dbid"),
        sa.UniqueConstraint("current"),
    )
    op.create_index(
        op.f("ix_scheduled_exam_package__row_created_at"),
        "scheduled_exam_package",
        ["_row_created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduled_exam_package_external_id"),
        "scheduled_exam_package",
        ["external_id"],
        unique=True,
    )
    op.create_table(
        "scheduled_exam",
        sa.Column("dbid", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("_row_created_at", sa.DateTime(), nullable=False),
        sa.Column("exam_file_info_dbid", sa.Integer(), nullable=False),
        sa.Column("scheduled_exam_package_dbid", sa.Integer(), nullable=True),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("exam_title", sa.String(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column("modified_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exam_file_info_dbid"],
            ["exam_file_info.dbid"],
        ),
        sa.ForeignKeyConstraint(
            ["scheduled_exam_package_dbid"],
            ["scheduled_exam_package.dbid"],
        ),
        sa.PrimaryKeyConstraint("dbid"),
    )
    op.create_index(
        op.f("ix_scheduled_exam__row_created_at"),
        "scheduled_exam",
        ["_row_created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduled_exam_external_id"),
        "scheduled_exam",
        ["external_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scheduled_exam_external_id"), table_name="scheduled_exam")
    op.drop_index(
        op.f("ix_scheduled_exam__row_created_at"), table_name="scheduled_exam"
    )
    op.drop_table("scheduled_exam")
    op.drop_index(
        op.f("ix_scheduled_exam_package_external_id"),
        table_name="scheduled_exam_package",
    )
    op.drop_index(
        op.f("ix_scheduled_exam_package__row_created_at"),
        table_name="scheduled_exam_package",
    )
    op.drop_table("scheduled_exam_package")
    op.drop_index(op.f("ix_exam_info_request_id"), table_name="exam_info")
    op.drop_index(op.f("ix_exam_info__row_created_at"), table_name="exam_info")
    op.drop_table("exam_info")
    op.drop_index(op.f("ix_exam_file_info_external_id"), table_name="exam_file_info")
    op.drop_table("exam_file_info")
    op.drop_index(
        op.f("ix_abitti2_status_report__row_created_at"),
        table_name="abitti2_status_report",
    )
    op.drop_table("abitti2_status_report")
    # ### end Alembic commands ###
