"""Add started_at and archived_at to exam packages

Revision ID: 4d51d9e18cdd
Revises: 623ee1244eb9
Create Date: 2026-03-08 14:56:33.240810

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4d51d9e18cdd"
down_revision: Union[str, Sequence[str], None] = "623ee1244eb9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scheduled_exam_package", sa.Column("started_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "scheduled_exam_package", sa.Column("archived_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scheduled_exam_package", "archived_at")
    op.drop_column("scheduled_exam_package", "started_at")
    # ### end Alembic commands ###
