"""Remove thing

Revision ID: 8f68ef9389a7
Revises: c5b126dcfbfc
Create Date: 2025-10-15 13:58:09.056765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8f68ef9389a7"
down_revision: Union[str, Sequence[str], None] = "c5b126dcfbfc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_things_id"), table_name="things")
    op.drop_index(op.f("ix_things_name"), table_name="things")
    op.drop_table("things")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "things",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("size", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_things_name"), "things", ["name"], unique=1)
    op.create_index(op.f("ix_things_id"), "things", ["id"], unique=False)
    # ### end Alembic commands ###
