"""add users roles and permissions

Revision ID: bb0203ef063b
Revises: 4d51d9e18cdd
Create Date: 2026-09-20 15:26:02.034886

"""

import datetime
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bb0203ef063b"
down_revision: str | Sequence[str] | None = "4d51d9e18cdd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Seed data: a default "invigilator" role granted the one permission
# needed by the existing WUI invigilator page, so that a username seen
# for the first time at login is auto-provisioned with the same access
# it already implicitly had under the old HTTP Basic Auth check.
_INVIGILATOR_ROLE_NAME = "invigilator"
_INVIGILATOR_VIEW_PERMISSION_NAME = "wui.invigilator.view"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column("dbid", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("dbrow_created_at", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("dbid"),
    )
    op.create_index(
        op.f("ix_permissions_dbrow_created_at"),
        "permissions",
        ["dbrow_created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_permissions_name"), "permissions", ["name"], unique=True)
    op.create_table(
        "roles",
        sa.Column("dbid", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("dbrow_created_at", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("dbid"),
    )
    op.create_index(
        op.f("ix_roles_dbrow_created_at"), "roles", ["dbrow_created_at"], unique=False
    )
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=True)
    op.create_table(
        "users",
        sa.Column("dbid", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("dbrow_created_at", sa.DateTime(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("dbid"),
    )
    op.create_index(
        op.f("ix_users_dbrow_created_at"), "users", ["dbrow_created_at"], unique=False
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "role_permission",
        sa.Column("role_dbid", sa.Integer(), nullable=False),
        sa.Column("permission_dbid", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_dbid"],
            ["permissions.dbid"],
        ),
        sa.ForeignKeyConstraint(
            ["role_dbid"],
            ["roles.dbid"],
        ),
        sa.PrimaryKeyConstraint("role_dbid", "permission_dbid"),
    )
    op.create_table(
        "user_role",
        sa.Column("user_dbid", sa.Integer(), nullable=False),
        sa.Column("role_dbid", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_dbid"],
            ["roles.dbid"],
        ),
        sa.ForeignKeyConstraint(
            ["user_dbid"],
            ["users.dbid"],
        ),
        sa.PrimaryKeyConstraint("user_dbid", "role_dbid"),
    )
    # ### end Alembic commands ###

    _seed_default_role_and_permission()


def _seed_default_role_and_permission() -> None:
    now = datetime.datetime.utcnow()

    permissions_table = sa.table(
        "permissions",
        sa.column("dbid", sa.Integer),
        sa.column("dbrow_created_at", sa.DateTime),
        sa.column("name", sa.String),
    )
    roles_table = sa.table(
        "roles",
        sa.column("dbid", sa.Integer),
        sa.column("dbrow_created_at", sa.DateTime),
        sa.column("name", sa.String),
    )
    role_permission_table = sa.table(
        "role_permission",
        sa.column("role_dbid", sa.Integer),
        sa.column("permission_dbid", sa.Integer),
    )

    conn = op.get_bind()

    conn.execute(
        sa.insert(permissions_table).values(
            dbrow_created_at=now, name=_INVIGILATOR_VIEW_PERMISSION_NAME
        )
    )
    permission_dbid = conn.execute(
        sa.select(permissions_table.c.dbid).where(
            permissions_table.c.name == _INVIGILATOR_VIEW_PERMISSION_NAME
        )
    ).scalar_one()

    conn.execute(
        sa.insert(roles_table).values(dbrow_created_at=now, name=_INVIGILATOR_ROLE_NAME)
    )
    role_dbid = conn.execute(
        sa.select(roles_table.c.dbid).where(
            roles_table.c.name == _INVIGILATOR_ROLE_NAME
        )
    ).scalar_one()

    conn.execute(
        sa.insert(role_permission_table).values(
            role_dbid=role_dbid, permission_dbid=permission_dbid
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_role")
    op.drop_table("role_permission")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_dbrow_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.drop_index(op.f("ix_roles_dbrow_created_at"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_permissions_name"), table_name="permissions")
    op.drop_index(op.f("ix_permissions_dbrow_created_at"), table_name="permissions")
    op.drop_table("permissions")
    # ### end Alembic commands ###
