"""Add ScheduledExamPackage.state_changed_at

Revision ID: cf3a53e8cfbd
Revises: 70456b673d46
Create Date: 2025-10-28 20:24:26.113238

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf3a53e8cfbd"
down_revision: str | Sequence[str] | None = "70456b673d46"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scheduled_exam_package",
        sa.Column("state_changed_at", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scheduled_exam_package", "state_changed_at")
    # ### end Alembic commands ###
