[supervisord]
logfile = logs/supervisord.log
pidfile = supervisord.pid
childlogdir = logs
nodaemon=True

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[unix_http_server]
file=ktp_controller_supervisor_sock
chmod=0700

[supervisorctl]
serverurl=unix://ktp_controller_supervisor_sock

[program:redis]
command=redis-server
autostart=true
autorestart=false
startsecs=0
stopasgroup=true
killasgroup=true

[program:deletedb]
command=rm -vf tests/ktp_controller.sqlite
autostart=false
autorestart=false
startsecs=0
stdout_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stderr_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stopasgroup=true
killasgroup=true

[program:migratedb]
command=uv run alembic upgrade head
environment=KTP_CONTROLLER_DOTENV=tests/integration_test.env
autostart=false
autorestart=false
startsecs=0
stdout_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stderr_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stopasgroup=true
killasgroup=true

[program:examomatic-mock]
command=uv run python3 -m ktp_controller.examomatic.mock
environment=KTP_CONTROLLER_DOTENV=tests/integration_test.env
autostart=false
autorestart=false
startsecs=0
stopasgroup=true
killasgroup=true

[program:api]
command=uv run python3 -m ktp_controller.api
environment=KTP_CONTROLLER_DOTENV=tests/integration_test.env
autostart=false
autorestart=false
startsecs=0
stopasgroup=true
killasgroup=true

[program:agent]
command=uv run python3 -m ktp_controller.agent
environment=KTP_CONTROLLER_DOTENV=tests/integration_test.env
autostart=false
autorestart=false
startsecs=0
stopasgroup=true
killasgroup=true

[program:pytest]
command=make pytest-integration
environment=KTP_CONTROLLER_DOTENV=tests/integration_test.env
autostart=false
autorestart=false
startretries=0
exitcodes=0
startsecs=0
stdout_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stderr_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stopasgroup=true
killasgroup=true

[eventlistener:chainer]
command='%(here)s/chainer' '%(here)s/integration-test.conf' redis deletedb WAIT migratedb WAIT examomatic-mock api agent pytest
events=PROCESS_STATE_RUNNING,PROCESS_STATE_EXITED,PROCESS_STATE_STOPPED,PROCESS_STATE_FATAL
