[supervisord]
logfile = logs/supervisord.log
pidfile = supervisord.pid
childlogdir = logs
nodaemon=True

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[unix_http_server]
file=ktp_controller_supervisor_sock
chmod=0700

[supervisorctl]
serverurl=unix://ktp_controller_supervisor_sock

[program:maybe-docker-pull]
command=sh -c 'if ! command -v redis-server; then docker pull redis:8.4.0; fi'
autostart=true
autorestart=false
startsecs=0
startretries=0
stdout_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stderr_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stopasgroup=true
killasgroup=true

[program:redis]
command=sh -c 'if command -v redis-server; then redis-server; else docker run --rm -p 6379:6379 --name ktp-controller-redis redis:8.4.0; fi'
autostart=false
autorestart=false
startsecs=5
startretries=0
stopasgroup=true
killasgroup=true

[program:deletedb]
command=rm -vf tests/ktp_controller.sqlite
autostart=false
autorestart=false
startsecs=0
startretries=0
stdout_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stderr_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stopasgroup=true
killasgroup=true

[program:migratedb]
command=uv run alembic upgrade head
autostart=false
autorestart=false
startsecs=0
startretries=0
stdout_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stderr_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stopasgroup=true
killasgroup=true

[program:examomatic-mock]
command=uv run python3 -m ktp_controller.examomatic.mock
autostart=false
autorestart=true
startsecs=5
startretries=0
stopasgroup=true
killasgroup=true

[program:api]
command=uv run python3 -m ktp_controller.api
autostart=false
autorestart=true
startsecs=5
startretries=0
stopasgroup=true
killasgroup=true

[program:agent]
command=uv run python3 -m ktp_controller.agent --testbed-mode
autostart=false
autorestart=true
startsecs=5
startretries=0
stopasgroup=true
killasgroup=true

[program:pytest]
command=make .pytest-integration
autostart=false
autorestart=false
startretries=0
exitcodes=0
startsecs=0
stdout_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stderr_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stopasgroup=true
killasgroup=true

[eventlistener:supervisor_chainer]
command=uv run python3 -m ktp_controller.supervisor_chainer '%(here)s/integration-test.conf' maybe-docker-pull WAIT redis deletedb WAIT migratedb WAIT examomatic-mock api agent pytest
events=PROCESS_STATE_RUNNING,PROCESS_STATE_EXITED,PROCESS_STATE_STOPPED,PROCESS_STATE_FATAL
