[supervisord]
logfile = syslog
syslog_name=ktp-controller-supervisord
pidfile = supervisord.pid
childlogdir = logs
nodaemon=True
nocleanup=true

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[unix_http_server]
file=ktp_controller_supervisor_sock
chmod=0700

[supervisorctl]
serverurl=unix://ktp_controller_supervisor_sock

[eventlistener:ktp-controller-supervisor-chainer]
buffer_size=100
command='%(here)s/bin/ktp-controller-supervisor-chainer' '%(here)s/puavo_os-prod-run.conf' ktp-controller-supervisor-chainer ktp-controller-migratedb WAIT ktp-controller-naksu2monitor ktp-controller-naksu2 ktp-controller-redis ktp-controller-api ktp-controller-agent
events=EVENT
stderr_syslog=true
stderr_logfile=none
stdout_logfile=none

[program:ktp-controller-migratedb]
command='%(here)s/bin/alembic' -c '%(here)s/alembic.ini' upgrade head
autostart=false
autorestart=false
stopasgroup=true
killasgroup=true
startsecs=0
startretries=0
exitcodes=0
stderr_syslog=true
stdout_syslog=true
stderr_logfile=none
stdout_logfile=none

[program:ktp-controller-redis]
command=redis-server
autostart=false
autorestart=true
stopasgroup=true
killasgroup=true
startsecs=5
startretries=999999
stderr_syslog=true
stdout_syslog=true
stderr_logfile=none
stdout_logfile=none

[program:ktp-controller-api]
command='%(here)s/bin/ktp-controller-api'
autostart=false
autorestart=true
stopasgroup=true
killasgroup=true
startsecs=5
startretries=999999
stderr_syslog=true
stdout_syslog=true
stderr_logfile=none
stdout_logfile=none

[program:ktp-controller-agent]
command=sudo -g puavo -n '%(here)s/bin/ktp-controller-agent'
autostart=false
autorestart=true
stopasgroup=true
killasgroup=true
startsecs=5
startretries=999999
stopwaitsecs=20
stderr_syslog=true
stdout_syslog=true
stderr_logfile=none
stdout_logfile=none

[program:ktp-controller-naksu2]
command=/usr/bin/puavo-ers-naksu2
autostart=false
autorestart=true
stopasgroup=true
killasgroup=true
startsecs=30
stopsignal=INT
stderr_syslog=true
stdout_syslog=true
stderr_logfile=none
stdout_logfile=none

[program:ktp-controller-naksu2monitor]
command=sh -c '%(here)s/bin/ktp-controller-naksu2monitor && sleep 31'
autostart=false
autorestart=unexpected
stopasgroup=true
killasgroup=true
startsecs=30
startretries=999999
exitcodes=0
stderr_syslog=true
stdout_syslog=true
stderr_logfile=none
stdout_logfile=none
